export const ORDER_STATUS = Object.freeze({
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RESCHEDULED: 'RESCHEDULED',
  RETURN_TO_ORIGIN: 'RETURN_TO_ORIGIN',
});

export const ORDER_STATUS_VALUES = Object.freeze(Object.values(ORDER_STATUS));